import { useEffect, useMemo, useState } from 'react';
import { cards, families, rarities, type CardData } from './data/gameCards';
import { addCards, loadCollection, ownedCount, saveCollection, type OwnedCards } from './data/collection';
import { battleVictory, buyBooster, loadProgression, saveProgression, xpForLevel, type Progression } from './data/progression';
import { DECK_SIZE, deckCards, loadDeck, saveDeck, starterDeck, validateDeck, type SavedDeck } from './data/deck';
import { BattleArena } from './BattleArena';
import { BalanceLab } from './BalanceLab';

type Screen='home'|'battle'|'boosters'|'collection'|'deck'|'balance'|'assets'|'shop'|'profile';
type AssetManifest={sourceZip:string;count:number;entries:string[]};
const generatedBase='/assets/generated/';
const familySheet:Record<string,string>={Magiciens:'chatgpt-image-7-sept.-2026-15_03_35.webp',Ombres:'chatgpt-image-7-sept.-2026-15_03_31.webp',Nobles:'chatgpt-image-7-sept.-2026-15_07_01.webp',Robots:'chatgpt-image-7-sept.-2026-15_01_47.webp',Nature:'chatgpt-image-7-sept.-2026-22_07_59.webp',Guérisseurs:'chatgpt-image-7-sept.-2026-15_03_15.webp',Créatures:'chatgpt-image-7-sept.-2026-15_04_45.webp',Pirates:'chatgpt-image-5-sept.-2026-23_17_33.webp',Éléments:'chatgpt-image-7-sept.-2026-15_04_34.webp',Armée:'plateau-salle-du-trone.webp'};

export function App(){
 const[screen,setScreen]=useState<Screen>('home');
 const[owned,setOwned]=useState<OwnedCards>(()=>loadCollection());
 const[progress,setProgress]=useState<Progression>(()=>loadProgression());
 const[deck,setDeck]=useState<SavedDeck>(()=>loadDeck()||starterDeck(cards,loadCollection()));
 useEffect(()=>saveCollection(owned),[owned]);useEffect(()=>saveProgression(progress),[progress]);useEffect(()=>saveDeck(deck),[deck]);
 useEffect(()=>{const checked=validateDeck(deck,cards,owned);if(checked.cardIds.length!==deck.cardIds.length)setDeck(d=>({...d,cardIds:checked.cardIds,updatedAt:Date.now()}))},[owned]);
 const battlePool=deckCards(deck,cards,owned);
 const deckValidation=validateDeck(deck,cards,owned);
 const win=()=>setProgress(p=>battleVictory(p));
 const lose=()=>setProgress(p=>({...p,losses:p.losses+1}));
 function buy(){const n=buyBooster(progress,100);if(!n)return false;setProgress(n);setScreen('boosters');return true}
 return <div className="app-shell"><header className="topbar"><button className="brand" onClick={()=>setScreen('home')}>PAW & CLAW</button><div className="tagline">Différentes âmes. Même arène.</div><div className="currency"><span>Niveau {progress.level}</span><span>Cartes {ownedCount(owned)}</span><span>Pièces {progress.coins}</span></div></header><nav className="nav-row">{(['home','battle','boosters','collection','deck','balance','shop','profile','assets'] as Screen[]).map(x=><button key={x} className={screen===x?'active':''} onClick={()=>setScreen(x)}>{navLabel(x)}</button>)}</nav><main>{screen==='home'&&<Home go={setScreen}/>} {screen==='battle'&&(deckValidation.valid&&battlePool.length===DECK_SIZE?<BattleArena playerPool={battlePool} onWin={win} onLose={lose}/>:<InvalidDeck go={setScreen} count={battlePool.length}/>)} {screen==='collection'&&<Collection owned={owned}/>} {screen==='boosters'&&<BoosterRoom onPull={pull=>{setOwned(o=>addCards(o,pull));setProgress(p=>({...p,boostersOpened:p.boostersOpened+1}))}}/>} {screen==='deck'&&<DeckBuilder owned={owned} deck={deck} onDeckChange={setDeck}/>} {screen==='balance'&&<BalanceLab/>} {screen==='shop'&&<Shop progress={progress} onBuy={buy}/>} {screen==='profile'&&<Profile progress={progress} owned={owned}/>} {screen==='assets'&&<AssetsLibrary/>}</main></div>
}
function Home({go}:{go:(s:Screen)=>void}){return <section className="home-hero"><div className="hero-copy"><p className="eyebrow">COLLECTION · COMBAT · PROGRESSION</p><h1>Bienvenue dans l’arène</h1><p>Collectionne les chats et chiens de chaque faction, construis ton deck et affronte le rival dans une arène fantasy pensée pour le jeu en paysage.</p><div className="hero-actions"><button className="primary" onClick={()=>go('battle')}>Jouer maintenant</button><button onClick={()=>go('boosters')}>Ouvrir un booster</button><button onClick={()=>go('collection')}>Ma collection</button></div></div><div className="home-visual"><img src={`${generatedBase}heros-duo.webp`} alt="Héros Paw & Claw"/></div></section>}
function InvalidDeck({go,count}:{go:(s:Screen)=>void;count:number}){return <section className="placeholder"><h2>Deck incomplet</h2><p>Ton deck actif contient {count}/{DECK_SIZE} cartes valides. Complète-le avant de lancer un combat.</p><button className="primary" onClick={()=>go('deck')}>Ouvrir le Deck Builder</button></section>}
function Collection({owned}:{owned:OwnedCards}){const[family,setFamily]=useState<(typeof families)[number]>('Tous'),[rarity,setRarity]=useState<(typeof rarities)[number]>('Toutes'),[query,setQuery]=useState('');const filtered=useMemo(()=>cards.filter(c=>(family==='Tous'||c.family===family)&&(rarity==='Toutes'||c.rarity===rarity)&&c.name.toLowerCase().includes(query.toLowerCase())),[family,rarity,query]);return <section className="collection-screen"><div className="collection-head"><div><p className="eyebrow">BIBLIOTHÈQUE</p><h2>Collection Paw & Claw</h2><p>{Object.keys(owned).filter(id=>owned[id]>0).length}/{cards.length} cartes découvertes · {ownedCount(owned)} exemplaires.</p></div><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher une carte…"/></div><div className="family-strip">{families.slice(1).map(n=><button key={n} onClick={()=>setFamily(n)} className={family===n?'active':''}>{n}<span>{cards.filter(c=>c.family===n).length}</span></button>)}</div><div className="filter-row"><button className={family==='Tous'?'active':''} onClick={()=>setFamily('Tous')}>Toutes</button>{rarities.map(r=><button key={r} className={rarity===r?'active':''} onClick={()=>setRarity(r)}>{r}</button>)}</div><div className="collection-grid">{filtered.map(c=><CatalogCard key={c.id} card={c} copies={owned[c.id]??0}/>)}</div></section>}
function CardImage({card}:{card:CardData}){const fallback=familySheet[card.family]?`${generatedBase}${familySheet[card.family]}`:`${generatedBase}carte-bleue.webp`;const[src,setSrc]=useState(card.assetPath??fallback);useEffect(()=>setSrc(card.assetPath??fallback),[card.id]);return <img src={src} alt={card.name} onError={()=>src!==fallback&&setSrc(fallback)} loading="lazy"/>}
function CatalogCard({card,copies}:{card:CardData;copies?:number}){return <article className={`catalog-card ${rarityClass(card.rarity)} ${copies===0?'locked':''}`}><div className="catalog-art"><CardImage card={card}/><span className="catalog-cost">{card.cost}</span><span className="catalog-family">{card.family}</span>{copies!==undefined&&<span className="owned-badge">×{copies}</span>}</div><div className="catalog-body"><div className="rarity-line"><span>{card.rarity}</span><span>{card.type}</span></div><h3>{card.name}</h3><p>{copies===0?'Carte non découverte':card.flavor??card.family}</p>{card.type==='Héros'&&<div className="stats"><span>ATQ {card.atk}</span><span>PV {card.hp}</span></div>}</div></article>}
function BoosterRoom({onPull}:{onPull:(c:CardData[])=>void}){const[opened,setOpened]=useState<CardData[]>([]);function open(){const pull=[...shuffle(cards.filter(c=>c.rarity==='Commune')).slice(0,8),...shuffle(cards.filter(c=>c.rarity==='Rare')).slice(0,3),...shuffle(cards.filter(c=>c.rarity==='Épique'||c.rarity==='Légendaire')).slice(0,1)];setOpened(pull);onPull(pull)}return <section className="booster-screen"><div className="booster-pack visual-pack"><img src={`${generatedBase}booster-violet.webp`} alt="Booster"/><button className="primary" onClick={open}>{opened.length?'Ouvrir encore':'Ouvrir le booster'}</button></div><div className="booster-results">{opened.map((c,i)=><CatalogCard key={c.id+i} card={c}/>)}</div></section>}
function DeckBuilder({owned,deck,onDeckChange}:{owned:OwnedCards;deck:SavedDeck;onDeckChange:(d:SavedDeck)=>void}){const pool=cards.filter(c=>c.type==='Héros'&&(owned[c.id]??0)>0);const validation=validateDeck(deck,cards,owned);const deckSet=new Set(deck.cardIds);const familyCounts=deck.cardIds.map(id=>cards.find(c=>c.id===id)?.family).filter(Boolean).reduce<Record<string,number>>((acc,f)=>{acc[f as string]=(acc[f as string]||0)+1;return acc},{});function setIds(cardIds:string[]){onDeckChange({...deck,cardIds,updatedAt:Date.now()})}return <section className="deck-screen"><div className="collection-head"><div><p className="eyebrow">DECK BUILDER</p><h2>{deck.name}</h2><p>{deck.cardIds.length}/{DECK_SIZE} · deck sauvegardé automatiquement · utilisé en combat</p></div><span className={`deck-validity ${validation.valid?'valid':'invalid'}`}>{validation.valid?'PRÊT POUR LE COMBAT':'DECK INCOMPLET'}</span></div><div className="deck-synergy-preview">{Object.entries(familyCounts).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([family,count])=><span key={family}>{family} {count}/{count>=5?5:count>=3?5:3}</span>)}</div><div className="deck-columns"><div><h3>Deck actuel</h3><div className="deck-list">{deck.cardIds.map(id=>cards.find(c=>c.id===id)!).filter(Boolean).map(c=><button key={c.id} onClick={()=>setIds(deck.cardIds.filter(x=>x!==c.id))}><span>{c.family} · {c.name}</span><span>Retirer</span></button>)}</div></div><div><h3>Disponibles</h3><div className="deck-list">{pool.filter(c=>!deckSet.has(c.id)).map(c=><button key={c.id} disabled={deck.cardIds.length>=DECK_SIZE} onClick={()=>setIds([...deck.cardIds,c.id])}><span>{c.family} · {c.name}</span><span>Ajouter</span></button>)}</div></div></div></section>}
function Shop({progress,onBuy}:{progress:Progression;onBuy:()=>boolean}){const[msg,setMsg]=useState('');return <section className="collection-screen"><div className="collection-head"><div><p className="eyebrow">BOUTIQUE</p><h2>Marché Paw & Claw</h2><p>Utilise les pièces gagnées en combat.</p></div><strong>{progress.coins} pièces</strong></div><div className="shop-grid"><article className="shop-item"><img src={`${generatedBase}booster-violet.webp`} alt="Booster standard"/><h3>Booster Royaume</h3><p>12 cartes : 8 communes, 3 rares, 1 épique ou légendaire.</p><button className="primary" onClick={()=>setMsg(onBuy()?'Booster acheté !':'Pas assez de pièces.')}>100 pièces</button></article><article className="shop-item disabled"><div className="shop-coming">Premium</div><h3>Booster Premium</h3><p>Arrive bientôt.</p><button disabled>Bientôt</button></article></div>{msg&&<p className="shop-message">{msg}</p>}</section>}
function Profile({progress,owned}:{progress:Progression;owned:OwnedCards}){const need=xpForLevel(progress.level),discovered=Object.keys(owned).filter(id=>owned[id]>0).length;return <section className="collection-screen"><div className="profile-card"><div className="profile-avatar">P&C</div><div><p className="eyebrow">PROFIL JOUEUR</p><h2>Niveau {progress.level}</h2><div className="xp-bar"><span style={{width:`${Math.min(100,progress.xp/need*100)}%`}}/></div><p>{progress.xp}/{need} XP</p></div></div><div className="profile-stats"><div><strong>{progress.wins}</strong><span>Victoires</span></div><div><strong>{progress.losses}</strong><span>Défaites</span></div><div><strong>{progress.boostersOpened}</strong><span>Boosters</span></div><div><strong>{discovered}</strong><span>Cartes découvertes</span></div><div><strong>{progress.coins}</strong><span>Pièces</span></div></div></section>}
function AssetsLibrary(){const[m,setM]=useState<AssetManifest|null>(null);useEffect(()=>{fetch(`${generatedBase}manifest.json`).then(r=>r.json()).then(setM).catch(()=>{})},[]);return <section className="collection-screen"><div className="collection-head"><div><p className="eyebrow">ASSETS</p><h2>Bibliothèque visuelle</h2><p>{m?.count??0} images du pack source.</p></div></div><div className="asset-grid">{(m?.entries??[]).map(n=><article className="asset-tile" key={n}><img src={`${generatedBase}${n}`} alt="" loading="lazy"/><small>{n}</small></article>)}</div></section>}
function navLabel(s:Screen){return({home:'Accueil',battle:'Combat',boosters:'Boosters',collection:'Collection',deck:'Deck',balance:'Équilibrage',shop:'Boutique',profile:'Profil',assets:'Assets'} as Record<Screen,string>)[s]}
function rarityClass(r:string){return r.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}function shuffle<T>(a:T[]){return [...a].sort(()=>Math.random()-.5)}
