import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { cards, families, rarities, type CardData } from './data/gameCards';
import { addCards, loadCollection, ownedCount, saveCollection, type OwnedCards } from './data/collection';
import { battleDefeat, battleDraw, battleVictory, buyBooster, loadProgression, openBooster, saveProgression, xpForLevel, type Progression } from './data/progression';
import { DECK_SIZE, deckCards, loadDeck, saveDeck, starterDeck, validateDeck, type SavedDeck } from './data/deck';
import { speciesOf } from './data/loreSynergies';
import { claimMission, loadMissionProgress, recordMission, saveMissionProgress, type MissionProgress } from './data/missions';
import { addBattlePassXp, claimPassReward, loadBattlePass, saveBattlePass, unlockPremium, type BattlePassState, type PassReward } from './data/battlePass';
import { loadMonetization,saveMonetization,type MonetizationState } from './data/monetization';
import { Matchmaking } from './Matchmaking';
import { BalanceLab } from './BalanceLab';
import { DeckStudio } from './DeckStudio';
import { ProgressionHub } from './ProgressionHub';
import { PortraitShop } from './PortraitShop';
import {GameNavigation,GameHeader,type GameScreen} from './GameNavigation';
import { BoosterOpening } from './BoosterOpening';
import { RealmHome } from './RealmHome';
import { GameAsset } from './GameAsset';
import {GameCard} from './GameCard';

type Screen=GameScreen;
type AssetManifest={sourceZip:string;count:number;entries:string[]};
const generatedBase='/assets/generated/';


function ScreenBackdrop({assetId,children,className='' }:{assetId:string;children:ReactNode;className?:string}){return <section className={`screen-with-background ${className}`.trim()}><GameAsset assetId={assetId} className="screen-background-art" decorative loading="eager"/><div className="screen-background-scrim"/><div className="screen-background-content">{children}</div></section>}

export function App(){
 const[screen,setScreen]=useState<Screen>('home');
 const[owned,setOwned]=useState<OwnedCards>(()=>loadCollection());
 const[progress,setProgress]=useState<Progression>(()=>loadProgression());
 const[deck,setDeck]=useState<SavedDeck>(()=>loadDeck()||starterDeck(cards,loadCollection()));
 const[missions,setMissions]=useState<MissionProgress>(()=>loadMissionProgress());
 const[pass,setPass]=useState<BattlePassState>(()=>loadBattlePass());
 const[monetization]=useState<MonetizationState>(()=>loadMonetization());
 useEffect(()=>saveCollection(owned),[owned]);useEffect(()=>saveProgression(progress),[progress]);useEffect(()=>saveDeck(deck),[deck]);useEffect(()=>saveMissionProgress(missions),[missions]);useEffect(()=>saveBattlePass(pass),[pass]);useEffect(()=>saveMonetization(monetization),[monetization]);
 useEffect(()=>{const checked=validateDeck(deck,cards,owned);if(checked.cardIds.length!==deck.cardIds.length)setDeck(d=>({...d,cardIds:checked.cardIds,updatedAt:Date.now()}))},[owned]);
 const battlePool=deckCards(deck,cards,owned);const deckValidation=validateDeck(deck,cards,owned);
 const win=()=>{setProgress(p=>battleVictory(p));setMissions(m=>recordMission(recordMission(m,'play'),'win'));setPass(p=>addBattlePassXp(p,25))};
 const lose=()=>{setProgress(p=>battleDefeat(p));setMissions(m=>recordMission(m,'play'));setPass(p=>addBattlePassXp(p,15))};
 const draw=()=>{setProgress(p=>battleDraw(p));setMissions(m=>recordMission(m,'play'));setPass(p=>addBattlePassXp(p,20))};
 function buy(){const n=buyBooster(progress,100);if(!n)return false;setProgress(n);setScreen('boosters');return true}
 function openPack(pull:CardData[]){const next=openBooster(progress);if(!next)return false;setProgress(next);setOwned(o=>addCards(o,pull));setMissions(m=>recordMission(m,'open-booster'));setPass(p=>addBattlePassXp(p,10));return true}
 function rewardProgress(p:Progression,reward:PassReward){if(reward.type==='coins')return{...p,coins:p.coins+reward.amount};if(reward.type==='gems')return{...p,gems:p.gems+reward.amount};return{...p,sealedBoosters:p.sealedBoosters+reward.amount}}
 function claimMissionReward(id:string){const result=claimMission(missions,id);if(!result)return;setMissions(result.state);setProgress(p=>({...p,coins:p.coins+result.mission.coins,gems:p.gems+result.mission.gems}));setPass(p=>addBattlePassXp(p,result.mission.passXp))}
 function claimPass(level:number,lane:'free'|'premium'){const result=claimPassReward(pass,level,lane);if(!result)return;setPass(result.state);setProgress(p=>rewardProgress(p,result.reward))}
 function activatePremium(){if(pass.premium||progress.gems<600)return;setProgress(p=>({...p,gems:p.gems-600}));setPass(p=>unlockPremium(p))}
 return <div className={`app-shell portrait-app ${screen==='battle'?'battle-mode':''}`}><GameHeader screen={screen} progress={progress} onNavigate={setScreen}/><GameNavigation screen={screen} onNavigate={setScreen}/><main key={screen} className="realm-screen-transition">{screen==='home'&&<RealmHome progress={progress} missions={missions} ownedCount={ownedCount(owned)} onNavigate={target=>setScreen(target)}/>} {screen==='battle'&&(deckValidation.valid&&battlePool.length===DECK_SIZE?<Matchmaking playerPool={battlePool} onWin={win} onLose={lose} onDraw={draw} onEditDeck={()=>setScreen('deck')}/>:<InvalidDeck go={setScreen} count={battlePool.length} issues={deckValidation.issues}/>)} {screen==='collection'&&<ScreenBackdrop assetId="world.collection-hall" className="collection-world"><Collection owned={owned}/></ScreenBackdrop>} {screen==='boosters'&&<BoosterOpening owned={owned} available={progress.sealedBoosters} onOpen={openPack} onShop={()=>setScreen('shop')}/>} {screen==='deck'&&<ScreenBackdrop assetId="world.deck-forge" className="deck-world"><DeckStudio owned={owned} activeDeck={deck} onActiveDeckChange={setDeck} onPlay={()=>setScreen('battle')}/></ScreenBackdrop>} {screen==='progression'&&<ScreenBackdrop assetId="world.events" className="events-world"><ProgressionHub progress={progress} missions={missions} pass={pass} onClaimMission={claimMissionReward} onClaimPass={claimPass} onUnlockPremium={activatePremium}/></ScreenBackdrop>} {screen==='balance'&&<BalanceLab/>} {screen==='shop'&&<ScreenBackdrop assetId="world.shop" className="shop-world"><PortraitShop progress={progress} onBuy={buy} onOpen={()=>setScreen('boosters')} monetization={monetization}/></ScreenBackdrop>} {screen==='profile'&&<Profile progress={progress} owned={owned}/>} {screen==='assets'&&<AssetsLibrary/>}</main></div>
}
function InvalidDeck({go,count,issues}:{go:(s:Screen)=>void;count:number;issues:string[]}){return <section className="placeholder"><h2>Deck non prêt</h2><p>Ton deck actif contient {count}/{DECK_SIZE} cartes valides. Un deck compétitif doit être composé uniquement de Moustaches ou uniquement de Truffes.</p>{issues.length>0&&<div className="deck-issues">{issues.slice(0,4).map(x=><p key={x}>{x}</p>)}</div>}<button className="primary" onClick={()=>go('deck')}>Préparer mon équipe</button></section>}
function Collection({owned}:{owned:OwnedCards}){const[family,setFamily]=useState<(typeof families)[number]>('Tous'),[rarity,setRarity]=useState<(typeof rarities)[number]>('Toutes'),[query,setQuery]=useState(''),[ownership,setOwnership]=useState<'all'|'owned'|'missing'>('all'),[selected,setSelected]=useState<CardData|null>(null);const filtered=useMemo(()=>cards.filter(c=>(family==='Tous'||c.family===family)&&(rarity==='Toutes'||c.rarity===rarity)&&c.name.toLowerCase().includes(query.toLowerCase())&&(ownership==='all'||(ownership==='owned'?(owned[c.id]??0)>0:(owned[c.id]??0)===0))),[family,rarity,query,ownership,owned]);const discovered=cards.filter(c=>(owned[c.id]??0)>0).length,legendary=cards.filter(c=>c.rarity==='Légendaire'&&(owned[c.id]??0)>0).length;return <section className="collection-screen"><div className="collection-head"><div><p className="eyebrow">GRIMOIRE ROYAL</p><h2>Galerie royale</h2></div><div className="collection-progress"><span><b>{discovered}</b>/{cards.length} découvertes</span><i><b style={{width:`${discovered/cards.length*100}%`}}/></i><small>{legendary} légendaires · {ownedCount(owned)} cartes</small></div><input className="search" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Rechercher une carte" placeholder="Rechercher…"/></div><div className="family-strip" aria-label="Familles de cartes"><button onClick={()=>setFamily('Tous')} className={family==='Tous'?'active':''}>Toutes</button>{families.slice(1).map(n=><button key={n} onClick={()=>setFamily(n)} className={family===n?'active':''}>{n}<span>{cards.filter(c=>c.family===n).length}</span></button>)}</div><div className="filter-row" aria-label="Filtres de collection">{rarities.map(r=><button key={r} className={rarity===r?'active':''} onClick={()=>setRarity(r)}>{r}</button>)}<button className={ownership==='owned'?'active':''} onClick={()=>setOwnership(ownership==='owned'?'all':'owned')}>Possédées</button><button className={ownership==='missing'?'active':''} onClick={()=>setOwnership(ownership==='missing'?'all':'missing')}>Manquantes</button></div><div className="collection-grid">{filtered.map(c=><CatalogCard key={c.id} card={c} copies={owned[c.id]??0} onSelect={()=>setSelected(c)}/>)}</div>{selected&&<div className="collection-card-sheet" role="dialog" aria-modal="true" aria-label={`Détails de ${selected.name}`}><button className="card-sheet-close" onClick={()=>setSelected(null)} aria-label="Fermer">×</button><div className="card-sheet-feature"><GameCard card={selected} variant="feature" copies={owned[selected.id]??0} locked={(owned[selected.id]??0)===0}/></div><div className="card-sheet-copy"><span>{selected.family} · {selected.rarity} · {selected.type}</span><h3>{selected.name}</h3><p>{(owned[selected.id]??0)>0?(selected.flavor??'Carte de la collection royale.'):'Cette carte reste à découvrir.'}</p><small>Possédée ×{owned[selected.id]??0}</small></div></div>}</section>}
function CatalogCard({card,copies,onSelect}:{card:CardData;copies?:number;onSelect?:()=>void}){return <article className="catalog-card game-card-host"><button className="catalog-card-button" onClick={onSelect} aria-label={`Voir ${card.name}`}><GameCard card={card} variant="standard" copies={copies} locked={copies===0}/></button></article>}
function Profile({progress,owned}:{progress:Progression;owned:OwnedCards}){const need=xpForLevel(progress.level),discovered=Object.keys(owned).filter(id=>owned[id]>0).length;return <section className="collection-screen"><div className="profile-card"><div className="profile-avatar">P&C</div><div><p className="eyebrow">PROFIL JOUEUR</p><h2>Niveau {progress.level}</h2><div className="xp-bar"><span style={{width:`${Math.min(100,progress.xp/need*100)}%`}}/></div><p>{progress.xp}/{need} XP</p></div></div><div className="profile-stats"><div><strong>{progress.wins}</strong><span>Victoires</span></div><div><strong>{progress.losses}</strong><span>Défaites</span></div><div><strong>{progress.draws}</strong><span>Égalités</span></div><div><strong>{progress.boostersOpened}</strong><span>Boosters ouverts</span></div><div><strong>{progress.sealedBoosters}</strong><span>Boosters stockés</span></div><div><strong>{discovered}</strong><span>Cartes découvertes</span></div><div><strong>{progress.coins}</strong><span>Pièces</span></div><div><strong>{progress.gems}</strong><span>Gemmes</span></div></div></section>}
function AssetsLibrary(){const[m,setM]=useState<AssetManifest|null>(null);useEffect(()=>{fetch(`${generatedBase}manifest.json`).then(r=>r.json()).then(setM).catch(()=>{})},[]);return <section className="collection-screen"><div className="collection-head"><div><p className="eyebrow">ASSETS</p><h2>Bibliothèque visuelle</h2><p>{m?.count??0} images du pack source.</p></div></div><div className="asset-grid">{(m?.entries??[]).map(n=><article className="asset-tile" key={n}><img src={`${generatedBase}${n}`} alt="" loading="lazy"/><small>{n}</small></article>)}</div></section>}
