import { MISSIONS,type MissionProgress } from './data/missions';
import { PASS_TIERS,passLevel,type BattlePassState,type PassReward } from './data/battlePass';
import type { Progression } from './data/progression';

export function ProgressionHub({progress,missions,pass,onClaimMission,onClaimPass,onUnlockPremium}:{progress:Progression;missions:MissionProgress;pass:BattlePassState;onClaimMission:(id:string)=>void;onClaimPass:(level:number,lane:'free'|'premium')=>void;onUnlockPremium:()=>void}){
 const level=passLevel(pass),next=PASS_TIERS.find(t=>t.xp>pass.xp);
 return <section className="progression-hub">
  <div className="progression-hero"><div><p className="eyebrow">SAISON · MISSIONS · RÉCOMPENSES</p><h2>Passe de combat</h2><p>Progresse simplement en jouant. Les récompenses premium restent cosmétiques et économiques, jamais plus puissantes en combat.</p></div><div className="pass-summary"><span>Niveau <strong>{level}</strong></span><span>XP <strong>{pass.xp}{next?`/${next.xp}`:''}</strong></span><span>Saison <strong>{pass.season}</strong></span></div></div>
  <div className="mission-columns"><MissionGroup title="Missions quotidiennes" cadence="daily" state={missions} onClaim={onClaimMission}/><MissionGroup title="Missions hebdomadaires" cadence="weekly" state={missions} onClaim={onClaimMission}/></div>
  <div className="pass-head"><div><h3>Piste de récompenses</h3><p>La piste gratuite est ouverte à tous. La piste Premium coûte 600 gemmes pour la saison.</p></div>{pass.premium?<span className="premium-owned">PREMIUM ACTIF</span>:<button className="primary" disabled={progress.gems<600} onClick={onUnlockPremium}>Débloquer Premium · 600 gemmes</button>}</div>
  <div className="pass-track">{PASS_TIERS.map(t=><article key={t.level} className={`pass-tier ${pass.xp>=t.xp?'unlocked':'locked'}`}><div className="tier-level"><small>NIVEAU</small><strong>{t.level}</strong><span>{t.xp} XP</span></div><RewardCell title="GRATUIT" reward={t.free} available={pass.xp>=t.xp} claimed={pass.claimedFree.includes(t.level)} onClaim={()=>onClaimPass(t.level,'free')}/><RewardCell title="PREMIUM" reward={t.premium} available={pass.premium&&pass.xp>=t.xp} claimed={pass.claimedPremium.includes(t.level)} locked={!pass.premium} onClaim={()=>onClaimPass(t.level,'premium')}/></article>)}</div>
 </section>
}
function MissionGroup({title,cadence,state,onClaim}:{title:string;cadence:'daily'|'weekly';state:MissionProgress;onClaim:(id:string)=>void}){const rows=MISSIONS.filter(m=>m.cadence===cadence);return <div className="mission-panel"><h3>{title}</h3>{rows.map(m=>{const value=Math.min(m.target,state.counts[m.id]??0),done=value>=m.target,claimed=state.claimed.includes(m.id);return <article className={`mission-row ${done?'complete':''}`} key={m.id}><div><strong>{m.label}</strong><span>{m.description}</span><small>{m.coins} pièces{m.gems?` · ${m.gems} gemmes`:''} · {m.passXp} XP Passe</small></div><div className="mission-progress"><span>{value}/{m.target}</span><div><i style={{width:`${Math.min(100,value/m.target*100)}%`}}/></div>{claimed?<b>RÉCUPÉRÉ</b>:<button disabled={!done} onClick={()=>onClaim(m.id)}>Récupérer</button>}</div></article>})}</div>}
function RewardCell({title,reward,available,claimed,locked,onClaim}:{title:string;reward:PassReward;available:boolean;claimed:boolean;locked?:boolean;onClaim:()=>void}){return <div className={`reward-cell ${locked?'premium-locked':''}`}><small>{title}</small><strong>{reward.label}</strong>{locked?<span>Premium requis</span>:claimed?<span>Récupéré</span>:<button disabled={!available} onClick={onClaim}>{available?'Récupérer':'Verrouillé'}</button>}</div>}
